### ISSUE TITLE
README pls

### ISSUE THREAD

**Issue by stewwan** [TeamHive/capacitor-video-recorder#13]
at ios the camera just doesn't appear to me, is it supposed to? even with permissions enabled.

it would be nice to have at least a simple step by step in readme

**Comment by alphagamer7** [comment]
+1

**Comment by sean-perkins** [comment]
Completed in #16. Most likely your camera was added underneath your app. You can either position the native layer under or over the app. If over, you cannot put web UI on top of it. If under, you need to make all the layers transparent to allow the native layer to show through.
