### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by terranmarine** [TeamHive/capacitor-video-recorder#16]
Please provide a documentation for the plugin.

**Comment by tansah** [comment]
+1 for this.. honestly this might be a very useful plugin, but if you only put capacitor-video-recorder as documentation, i cant see how anyone including myself will try to incorporate this plugin to their capacitor projects

**Comment by sean-perkins** [comment]
Documentation added: https://github.com/TeamHive/capacitor-video-recorder/blob/master/README.md

In the future you can refer to the definitions file for any capacitor plugin to see what methods, properties, etc. are available. 

https://github.com/TeamHive/capacitor-video-recorder/blob/master/src/definitions.ts
